name: macOS Python Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.6" # Change to your version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run program
        run: python main.py
